# Generated by Django 4.2.7 on 2023-12-14 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardquest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='Trainer',
            new_name='trainer',
        ),
        migrations.RenameField(
            model_name='collection',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='pokemoncard',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='trainer',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
